### PR TITLE
Added persistence to log messages

### PR DESCRIPTION
**Pull request by lucblender**

### CODE REVIEW

**Review by cm0x4D — COMMENTED** [review]
We should just ensure that we will not save too many log messages into that database and that we can turn that feature off.

How about a configurable limit with a decent default value (number of message or maximal size on disk), when new ones arrive the older ones get erased. What do you think about that @lucblender?

**Comment by lucblender** [comment]
The feature can already be turned off with ch.hevs.cloudio.endpoint.persistence. I think we could definitely add a limit and make mapdb act as a rolled buffer.

**Comment by lucblender** [comment]
> How about a configurable limit with a decent default value (number of message or maximal size on disk

@cm0x4D Do you know if mapdb already does implement something similar?

**Comment by cm0x4D** [comment]
Not that I would know about.

**Comment by cm0x4D** [comment]
> The feature can already be turned off with ch.hevs.cloudio.endpoint.persistence.

Yes, globally for everything. But I would like to be abled to deactivate it just for the logs (for example ch.hevs.cloudio.endpoint.log-persistance-limit = 0).

**Comment by lucblender** [comment]
> > The feature can already be turned off with ch.hevs.cloudio.endpoint.persistence.
> 
> Yes, globally for everything. But I would like to be abled to deactivate it just for the logs (for example ch.hevs.cloudio.endpoint.log-persistance-limit = 0).

So the limit would only be for the logs and the update/transaction messages wouldn't have a limit?

**Comment by cm0x4D** [comment]
> So the limit would only be for the logs and the update/transaction messages wouldn't have a limit?

Good point. A limit for this could be quite useful too, so maybe a configurable limit for each type (update, logs) and 0 means deactivated.

**Comment by lucblender** [comment]
I'll create a new issue for it and try to work to create this new persistence system. Can you still validate this pull request? For now when we do logs when Endpoint is not configured or connection is lost we get so many error message everywhere

**Review by cm0x4D — APPROVED** [review]

**Pull request merged**
